runtime: nodejs24
instance_class: F1
service: default  # Changed to 'default'
env_variables:
  NODE_ENV: "production"
handlers:
  - url: /assets/(.*\.(js|css|png|jpg|jpeg|svg|ico|json|woff|woff2|ttf|eot))$
    static_files: dist/assets/\1
    upload: dist/assets/.*\.(js|css|png|jpg|jpeg|svg|ico|json|woff|woff2|ttf|eot)$
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "https://faith-connect-backend-1074840511461.asia-south1.r.appspot.com"
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
entrypoint: "serve -s dist -p 8080"