services:
  reactjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - "5173:5173"
    # volumes:
      # - ./src:/app/src
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: .env
          target: /app/.env
        - action: rebuild
          path: package.json
          target: /app/package.json
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     # environment:
#     #   MONGO_INITDB_ROOT_USERNAME: admin_user
#     #   MONGO_INITDB_ROOT_PASSWORD: admin_password
# volumes:
#   mongodb_data:
