server {
    listen 80;
    server_name app.harpazotech.com;

    # Server configuration for serving frontend static files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Handle React Router's client-side routing
        try_files $uri $uri/ /index.html;
    }

    # Reverse Proxy for connecting frontend to the NestJS backend internally
    location /api/ {
        # The trailing slash removes the /api prefix before passing the request to the backend
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
