services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/signatures:/app/public/signatures
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public/uploads
          target: /app/public/uploads
        - action: sync
          path: .env
          target: /app/.env
        - action: rebuild
          path: package.json
          target: /app/package.json

  # LocalStack mimics AWS services locally.
  # We only enable SQS (for email queuing).
  # Port 4566 is LocalStack's default - your NestJS app talks to this.
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs          # Only run the SQS service, nothing else
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - localstack_data:/var/lib/localstack

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongo-rs
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: admin_user
  #   #   MONGO_INITDB_ROOT_PASSWORD: admin_password

volumes:
  mongodb_data:
  localstack_data:

