services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public/uploads
          target: /app/public/uploads
        - action: sync
          path: .env
          target: /app/.env
        - action: rebuild
          path: package.json
          target: /app/package.json
  mongodb:
    image: mongo:latest
    container_name: mongo-rs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin_user
    #   MONGO_INITDB_ROOT_PASSWORD: admin_password
volumes:
  mongodb_data:
