export type TEventsData = {
  id?: string,
  eventName: string,
  startDate: Date | string,
  endDate?: Date | string,
  startTime?: string | null,
  endTime?: string | null,
  invitedGroups?: string[],
  description: string,
  eventLocation: string,
  organizer: string,
  createdDate?: string,
  isRecurring?: boolean,
  recurrenceType?: 'WEEKLY',
  recurrenceDay?: string,
  recurrenceEndDate?: string,
}